### ISSUE TITLE
[Feature REQ] Font support

### ISSUE THREAD

**Issue by filfat** [xerpi/sf2dlib#1]
It would be great if you in the future added support for font rendering with support for both ttf files loaded at run time and ttf files included as .h /.bin file(s).

**Comment by Lectem** [comment]
ttf loaded at runtime ? bwa.
Maybe have a look at smea's geoshader thing for this

**Comment by jerwuqu** [comment]
There's this https://github.com/smealum/ftpony/blob/d499b59deeadf0f8235061ec0001aaecc9ebacb8/source/text.c#L13

**Comment by filfat** [comment]
or you'know this https://github.com/xerpi/sftdlib
