### ISSUE TITLE
ctrulib update breaks rendering

### ISSUE THREAD

**Issue by uschmann** [xerpi/sf2dlib#11]
After the following commit sf2dlib breaks:
https://github.com/smealum/ctrulib/tree/11a5001f3321ce0deb62d79abfb62ac2ab54763a
Seems like GPU_DrawArray() was changed and sf2dlib needs to be adjusted.

**Comment by Lectem** [comment]
Please do not say "breaks rendering" this is misleading. It is a compilation problem.
The chqngelog is herehttps://github.com/smealum/ctrulib/commit/11a5001f3321ce0deb62d79abfb62ac2ab54763a
If it does break rendering, please describe it

**Comment by uschmann** [comment]
I did the following:
1. i updated ctrulib to the latest commit
2. compiled one of my apps that use sf2dlib.
3. run compiled app in citra
Result: The garbage was rendered on the screen.

To fix this temporary:
1. fetched out old version of ctrulib: 11a5001f3321ce0deb62d79abfb62ac2ab54763a
2. installed the old version of ctrulib
3. compiled and run my app again
Result: Screen was rendered as expected.

So yeah it´s an compilation and linking problem.
The signature of GPU_DrawArray() changed.
void GPU_DrawArray(GPU_Primitive_t primitive, u32 n, u32 first)
is now:
void GPU_DrawArray(GPU_Primitive_t primitive, u32 first, u32 count)

I try to fix it and make a pull request.

**Comment by Lectem** [comment]
The signature indeed changed to follow the opengl naming convention, just invert the two last arguments. ( first stays first, n became count)

**Comment by uschmann** [comment]
I updated all calls to GPU_DrawArray and made a pull request.
I tested it with my application and it now compiles and renders fine.
I close this issue for now.
