### ISSUE TITLE
Calling consoleInit with sf2dlib running results in a crash

### ISSUE THREAD

**Issue by flarn2006** [xerpi/sf2dlib#15]
I wanted to draw on the top screen with sf2dlib, and use ctrulib's built-in console on the bottom screen. But when I added the `consoleInit` call to my program, it crashed as soon as it started. I tried moving it to before the `sf2d_init` call, and the same thing happened.

I understand that normally it wouldn't make sense to be using two things that require a full screen to write to at once, but I'm writing a program for a device that has two screens, so I don't see why this shouldn't be possible.

**Comment by videah** [comment]
ctrulib's console works fine for me, as long as I'm not making a frame for that screen.

**Comment by flarn2006** [comment]
Oh, I just tried again and it worked fine. I figured the first time I had accidentally specified `GFX_TOP` instead of `GFX_BOTTOM`, but I tested that and it doesn't cause a crash, just garbled graphics. No idea what went wrong before. Thanks!
