### ISSUE TITLE
Update to work with latest version of ctrulib

### ISSUE THREAD

**Issue by JerwuQu** [xerpi/sf2dlib#17]
ctrulib has a new branch with updated functions for GPU/sound and lots of stuff. Please update or make another branch of sf2dlib to work with these changes :smile:

**Comment by retrohead** [comment]
I tried installing the latest ctrulib, sf2dlib and citra. I managed to compile the sample but I just get a red screen on NH2.5 on O3ds and citra is throwing all sorts of errors.

Is this the same issue or should I raise a new one?

**Comment by profi200** [comment]
The great-refactor branch is not yet ready. There is a lot to be changed still. I would keep using master until it is ready.

**Comment by retrohead** [comment]
I used the master branch so guess mine is a different issue.

**Comment by xerpi** [comment]
I'll update sf2d when ctrulib upstreams the refactor.

**Comment by Ihamfp** [comment]
The "great refactor" branch has been merged to the master one, and a new ctrulib version has been created.
You can now update your lib :smile:
