### ISSUE TITLE
Trying to get the .exe file?

### ISSUE THREAD

**Issue by alkaseltzerspadt** [xerpi/sf2dlib#19]
So I am trying to comple something and I have prepared everything.  It works very well up until it returns this to me:
linking PCHex++.elf
f:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lsftd
f:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-e
abi/bin/ld.exe: cannot find -lsf2d
collect2.exe: error: ld returned 1 exit status
make[1]: **\* [/f/PCHex-plusplus-master/PCHex++.elf] Error 1
make: **\* [build] Error 2

Does anyone have any suggestions?  I think what it is trying to tell me is I need the lsf3d.exe file in the bin folder of the "devkitPro."  Any help is greatly appreciated.  Thanks and have a great day/evening.

**Comment by profi200** [comment]
-l is a linker flag and imagine the l is "lib" so you get "libsf2d" and "libsftd". It complains that it can't find the library files "libsf2d.a" and "libsftd.a".

**Comment by alkaseltzerspadt** [comment]
@profi200 Where should that "libsft2.a" file go?  Sorry for the "childish" questions.  I am quite ignorant in this area of technology.

**Comment by xerpi** [comment]
@amspady20 Download sf2dlib and make install it, the same with libsftd (https://github.com/xerpi/sftdlib) then you will be able to compile PCHex.

**Comment by alkaseltzerspadt** [comment]
@xerpi Thanks.  I really appericate the help.  Have a nice night.
