### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by filfat** [xerpi/sf2dlib#2]
There is no license in this project, should it be considered public domain?

**Comment by xerpi** [comment]
Do you think the MIT licence is good for this? Or (L)GPL?

**Comment by filfat** [comment]
MIT would probably be best for a lib as it doesn't force the user to open source parts or all of their software that uses this lib. (which means more users)

Sent from Windows Phone 8.1 on the Nokia Lumia 920
________________________________

**Comment by xerpi** [comment]
I've added MIT license, I can close this ;)
