### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Aurelio92** [xerpi/sf2dlib#20]
Hello, I've updated both ctrulib and sf2dlib and I get some graphic glitches on my 3DS trying to run the provided sample.
I've tried running the sample both through ninjhax2 that as a cia, nothing changes.
These are the screenshots of what I get:

![scr_1_top_left](https://cloud.githubusercontent.com/assets/6437036/11612809/a90aefb2-9c08-11e5-8b44-483448fece05.png)

![scr_1_bottom](https://cloud.githubusercontent.com/assets/6437036/11612808/a906cf7c-9c08-11e5-94b7-514ea4195f82.png)

Thanks

**Comment by xerpi** [comment]
Can you try commenting the sf2d_draw_fill_circle calls and see if it gets glitchy too?

**Comment by Aurelio92** [comment]
Nope, I still have the same glitches... Could you try to upload the compiled shader? Maybe I did something wrong installing picasso and it is compiling it wrongly

**Comment by xerpi** [comment]
Sure: 
[compiled_shader.zip](https://github.com/xerpi/sf2dlib/files/53129/compiled_shader.zip)

**Comment by Aurelio92** [comment]
Nope, still the same. I've also compared your compiled shader with mine (through md5) and they are equal. I don't know what to do...

**Comment by Aurelio92** [comment]
My mistake, sorry
