### ISSUE TITLE
Request: Drawing a texture to another texture.

### ISSUE THREAD

**Issue by Kyokyonos** [xerpi/sf2dlib#25]
Hello,

Given an empty texture, I'd like to draw/write to the texture a few times so that the result texture I draw to is just one texture itself. I'm guessing sf2d_textures are some kind of special buffers and the normal draw functions somehow tell the GPU to write what's in the texture buffer to the framebuffer... but I'm not so sure how I can do what I want. I'm basically generating images using many smaller images from a tilemap-- would it be slower to always redraw each part of the image (which doesn't change in the way it's drawn) or would it not make a difference to have the image as a single texture and draw that each frame?

This may be more of a sfillib request, but I'm wondering if there can be draw functions that draw textures (or parts of textures) to another texture's buffer instead of to the screen/framebuffer.  I really don't understand the ctrulib GPU rendering and triangles and stuff which is why I have been avoiding looking at the sf2dlib source code (I only understand software rendering RGB values to framebuffer). If it already exists, please let me know how it can be done. 

Thanks!

**Comment by xerpi** [comment]
That's a good idea but I've never done it and I'm not really sure how to do it. Btw I can add some optimizations when drawing the same image multiple times. Do you suffer an overhead when drawing the tilemap?

**Comment by Kyokyonos** [comment]
It could come down to me just using sf2dlib wrong or just having inefficient code elsewhere. A little context: I'm working on a simple gui engine for educational purposes and as an exercise for C++ inheritance and polymorphism. I've never made a ui tool/engine like this before.

![3DS UI](http://i.imgur.com/Ua1aDTa.png)

Since I wanted text with borders (and wasn't sure if sftdlib supported that) I wrote a quick bitmap text renderer using sf2dlib that uses a text bitmap image (so each character is essentially a tile)  and starling/unity compatible xml.

![Bitmap Text](http://i.imgur.com/uzNAZ87.png)

I might be using sf2dlib wrong because my initial implementation assumed you could draw to the screen only the parts that change. I could not figure out how to do this with sf2dlib so I redraw the entire screen (all objects) every main loop frame (it seemed like it would clear the screen or something instead of drawing on top of what was already in the framebuffer).

So anyways, the text is redrawn each frame even though it's not changing. I do quick visual tests using citra emulator and there is a noticeable difference in lag (the "TouchWagon" is something you can drag around) when I have a lot of text because each character is one call to sf2d_draw_texture_part() or something even though the text is not even changing.

Should I not be redrawing the entire screen each time? If I'm not supposed to do that, how can I have it so that when I call sf2d_draw_texture_part() it draws on top of whatever was there before?

But... there is no noticeable difference on the 3DS itself.. I think. I need to test it more vigorously. Overall, this may just be a premature optimization concern that I should/can just worry about later.

**Comment by xerpi** [comment]
Well, Citra emulator doesn't emulate at 100% of the 3DS speed (getting close over time but not there yet). sf2dlib uses the GPU, so screen clearing on each frame is very common in hardware accelerated apps. Can you send me your source so I can try it myself?

**Comment by Kyokyonos** [comment]
It could just come down to my inefficient bitmap text implementation. Nonetheless, it's very expensive at the moment on the physical 3DS. I made it so that when you press A, it draws 25 bitmap labels in the same spot. On my O3DS XL it doesn't look pretty when doing this (lol). Maybe I need to take a look at the sftd implementation for any hints on a better implementation.

https://www.dropbox.com/s/cb9nfarmcddwvly/hello-world-2-14-16.7z?dl=0

Anyways, the source is a real mess right now. It should include a precompiled 3dsx that demonstrates the problem that I think could be reduced if the text was a converted to a single texture instead of recalculating how it's drawn every frame because I currently just draw each character over and over which has a bit of overhead due to the various calculations required to produce the effect (e.g. cut off, centering). If I could form a single texture out of the parts, I was thinking would then be 25 calls to draw instead of 25*(string size + overhead) which is why I made this suggestion.

I also wanted to try having something like default buttons with custom sizes built from some type of 9-slice sprite or something, but now I'm not sure if it'll be easy if it needs to be recalculated each frame.

**Comment by xerpi** [comment]
Ok, after almost 2 hours of testing I think I've finally found where the problem is: if 3D is deactivated, drawing to the TOP_LEFT and TOP_RIGHT will go to the same framebuffer.
I recommend you to follow this draw order:
1) Top left
2) Top right
3) Bottom
And only do step 2 (top right) if you have called sf2d_set_3D(true);

**Comment by Kyokyonos** [comment]
Amazing! Just reordered the way I draw things like you said and it doesn't look as bad as it did before! I definitely think things are manageable now. I really appreciate you taking the time out to look at this.

Feel free to close this issue since things aren't as bad as I thought and this request probably isn't needed. Who knows, maybe I'll figure something out. Anyways, thanks again!

**Comment by xerpi** [comment]
Cool, good to hear!

**Comment by Kyokyonos** [comment]
Since I never like leaving unsolved problems, I actually was able to achieve a similar effect to I wanted (a 'part' version shouldn't be too hard). I saw that there were functions to get/set pixels in textures so I used them. I guess my only problem is that I have no idea how to manually alpha blend two RGBA8 pixels. I tried all sorts of formulas online and could get none of them to work properly.

```
void sf2d_write_texture(sf2d_texture* source, sf2d_texture* destination, int x, int y)
{
    if (!destination->tiled)
        sf2d_texture_tile32(destination);

    u32 a;
    u32 sr, sg, sb, sa;
    u32 dr, dg, db, da;
    u32 sourcePixel;
    u32 destinationPixel;
    for (unsigned int h = 0; h < source->height && y + h < destination->height; ++h) 
    {
        for (unsigned int w = 0; w < source->width && x + w < destination->width; ++w) 
        {

            destinationPixel = sf2d_get_pixel(destination, w, h);
            sourcePixel = sf2d_get_pixel(source, w, h);

            sa = RGBA8_GET_A(sourcePixel);
            da = RGBA8_GET_A(destinationPixel);

            sr = RGBA8_GET_R(sourcePixel);
            sg = RGBA8_GET_G(sourcePixel);
            sb = RGBA8_GET_B(sourcePixel);

            dr = RGBA8_GET_R(destinationPixel);
            dg = RGBA8_GET_G(destinationPixel);
            db = RGBA8_GET_B(destinationPixel);

            //Alpha blend magic?? Help?
            //dr = (sr * sa + dr * (255 - sa)) / 255;
            //dg = (sg * sa + dg * (255 - sa)) / 255;
            //db = (sb * sa + db * (255 - sa)) / 255;
            //a = ... ?

            sf2d_set_pixel(destination, x + w, y + h, RGBA8(sr, sg, sb, sa));

        }
    }
}
```

Using the above, I create a texture called "result" and copy/write "test" to it twice (in different positions).

```
sf2d_texture* result = sf2d_create_texture(test->width, test->height, TEXFMT_RGBA8, SF2D_PLACE_RAM);
sf2d_write_texture(test, result, 0, 0);
sf2d_write_texture(test, result, 30, 25);

while (aptMainLoop())
{

    sf2d_start_frame(GFX_TOP, GFX_LEFT);

    sf2d_draw_texture(result, 0, 5);
    sf2d_draw_texture(test, 0, 60);
    sf2d_draw_texture(result, 0, 100);

    sf2d_end_frame();

    sf2d_swapbuffers();
}
```

When drawn it looks like:

![result](http://i.imgur.com/01e6MWG.png)

The first image on the top is the new texture created from writing to an empty texture twice. The second image below that is the original texture. The third (slightly overlapping image) is the the new texture again, but showing that there is supposed to be transparency in the lighter oval which does not appear because I do not know how to calculate RBGA8 alpha.

I think this idea could be helpful even though it does not support true alpha overlaying. Maybe someone can figure out how to overlay two RBGA8 pixels? Nonetheless, this is enough to have my bitmap font implementation to spit out a single texture of text instead of redrawing each character every time.

Edit:

Little did I know, the BMP glyphs created in Photoshop have small amounts of transparency around the edges... causing the text to look cut off in lots of places. Guess I'll have to figure out the alpha part after all...

![test](http://i.imgur.com/Y2XlU2R.png)

**Comment by xerpi** [comment]
I'm not sure, but I think those are the equations you have to apply:
![image](https://upload.wikimedia.org/math/0/6/3/063478901c560e94a62ff0d69710157d.png)

**Comment by Kyokyonos** [comment]
Thanks for all of your help and support. Took me a few hours to get it working because I thought the formulas that I derived were wrong and kept trying to get a different answer. I needed to make values go from 0-255 instead of 0-1 ... and I'm not so great at that kind of conversion algebra.

Also, I was using the RGBA8 macros thinking they would help... but on closer inspection, the expansions do not appear to be in 0xRRGGBBAA format so I did it manually.

![result](http://i.imgur.com/qSfHyYh.png)

```
.
.
.
sf2d_texture* result = sf2d_create_texture(test->width, test->height, TEXFMT_RGBA8, SF2D_PLACE_RAM);
sf2d_write_texture_part(test, result, 30, 0, 50, 0, 100, 50);
sf2d_write_texture_part(test, result, 30, 0, 50, 0, 100, 50); //Same size/place as above, complete overlap.
sf2d_write_texture_part(test, result, 50, 25, 50, 0, 100, 50);

while (aptMainLoop())
    {

        sf2d_start_frame(GFX_TOP, GFX_LEFT);

        sf2d_draw_texture(result, 0, 5);
        sf2d_draw_texture(test, 0, 60);
        sf2d_draw_texture(result, 0, 100);

        sf2d_end_frame();

        sf2d_swapbuffers();
    }
.
.
.
```

Here is the code in case anyone else needs something similar. Inefficient to make, but using the result made some great speed ups in citra emulator at least. Not sure if it works in all cases, but I tried to test the major cases.

```
void sf2d_write_texture_part(sf2d_texture* source, sf2d_texture* destination, int x, int y, int tex_x, int tex_y, int tex_w, int tex_h)
{
    if (!destination->tiled)
    {
        sf2d_texture_tile32(destination);
        destination->tiled = true;
    }

    s32 out_a, out_r, out_g, out_b;
    s32 src_r, src_g, src_b, src_a;
    s32 dst_r, dst_g, dst_b, dst_a;
    u32 sourcePixel;
    u32 destinationPixel;

    for (int h = tex_y; h < tex_y + tex_h; ++h)
    {
        for (int w = tex_x; w < tex_x + tex_w; ++w)
        {
            if (x + (w - tex_x) < destination->width && y + (h - tex_y) < destination->height)
            {

                destinationPixel = sf2d_get_pixel(destination, x + (w - tex_x), y + (h - tex_y));
                sourcePixel = sf2d_get_pixel(source, w, h);

                src_a = sourcePixel & 0xFF;
                dst_a = destinationPixel & 0xFF;

                src_r = (sourcePixel & 0xFF000000) >> 24;
                src_g = (sourcePixel & 0x00FF0000) >> 16;
                src_b = (sourcePixel & 0x0000FF00) >> 8;

                dst_r = (destinationPixel & 0xFF000000) >> 24;
                dst_g = (destinationPixel & 0x00FF0000) >> 16;
                dst_b = (destinationPixel & 0x0000FF00) >> 8;

                out_a = src_a + ((dst_a * (255 - src_a)) / 255);
                out_r = ((src_r * src_a) + ((dst_r * dst_a * (255 - src_a)) / 255)) / out_a;
                out_g = ((src_g * src_a) + ((dst_g * dst_a * (255 - src_a)) / 255)) / out_a;
                out_b = ((src_b * src_a) + ((dst_b * dst_a * (255 - src_a)) / 255)) / out_a;

                if (out_a > 255) out_a = 255;
                if (out_r > 255) out_r = 255;
                if (out_g > 255) out_g = 255;
                if (out_b > 255) out_b = 255;

                sf2d_set_pixel(destination, x + (w - tex_x), y + (h - tex_y), (out_r << 24) | (out_g << 16) | (out_b << 8) | out_a);

            }
        }
    }
}
```

**Comment by xerpi** [comment]
I'm glad that you've managed to get it working. Maybe you can try to use GX_TextureCopy to speed up things.
