### ISSUE TITLE
[Issue (Request?)] :: Drawing one image at multiple coordinates

### ISSUE THREAD

**Issue by TurtleP** [xerpi/sf2dlib#31]
Hi,

I'm trying to make it so that I can take one image (a 16x16 image or even anything bigger) and a tile set image which is split up to draw at various locations to improve the drawing speeds.

I've modified the `sf2d_draw_texture_blend_generic` as follows:

//sf2d_texture.c
`static inline void sf2d_draw_texture_multi_generic(const sf2d_vertex_pos_tex _vertices, int x, int y)
{
    GPU_SetAttributeBuffers(
        2, // number of attributes
        (u32_)osConvertVirtToPhys(vertices),
        GPU_ATTRIBFMT(0, 3, GPU_FLOAT) | GPU_ATTRIBFMT(1, 2, GPU_FLOAT),
        0xFFFC, //0b1100
        0x10,
        1, //number of buffers
        (u32[]){0x0}, // buffer offsets (placeholders)
        (u64[]){0x10}, // attribute permutations for each buffer
        (u8[]){2} // number of attributes for each buffer
    );

```
GPU_DrawArray(GPU_TRIANGLE_STRIP, 0, 4);
```

}

void sf2d_draw_texture_multi(const sf2d_texture *texture, const sf2d_vertex_pos_tex \* vertices, int x, int y, u32 color)
{
    sf2d_bind_texture_color(texture, GPU_TEXUNIT0, color);
    sf2d_draw_texture_multi_generic(vertices, x, y);
}

//shared.h
typedef struct {
    love_image \* resource;

```
int maxImages;
int currentImage;

sf2d_vertex_pos_tex * * vertices;
```

} love_spritebatch;

//obj_spritebatch.c
const char \* spriteBatchInit(love_spritebatch \* self, love_image \* image, int maxImages) { //love.graphics.newSpriteBatch()

```
if (maxImages <= 0) {
    return "Invalid amount of max images: %d";
}

self->resource = image;

self->maxImages = maxImages;

self->currentImage = 0;

self->vertices = sf2d_pool_calloc(maxImages, sizeof(sf2d_vertex_pos_tex));

return NULL;
```

}

int spriteBatchAdd(lua_State \* L) { //Spritebatch:add()

```
love_spritebatch * self = luaobj_checkudata(L, 1, CLASS_TYPE);

if (self->currentImage >= self->maxImages) {
    lua_pushnumber(L, self->currentImage);

    return 1;
}

int x = luaL_checkinteger(L, 2);

int y = luaL_checkinteger(L, 3);

spriteBatchAddVerticies(self, self->resource->texture, x, y);

self->currentImage++;

lua_pushnumber(L, self->currentImage);

return 1;
```

}

void spriteBatchAddVerticies(love_spritebatch \* self, const sf2d_texture \* texture, int x, int y) {
    sf2d_vertex_pos_tex \* vertices = sf2d_pool_memalign(4 \* sizeof(sf2d_vertex_pos_tex), 8);
    if (!vertices) return;

```
int w = texture->width;
int h = texture->height;

vertices[0].position = (sf2d_vector_3f){(float)x,   (float)y,   SF2D_DEFAULT_DEPTH};
vertices[1].position = (sf2d_vector_3f){(float)x+w, (float)y,   SF2D_DEFAULT_DEPTH};
vertices[2].position = (sf2d_vector_3f){(float)x,   (float)y+h, SF2D_DEFAULT_DEPTH};
vertices[3].position = (sf2d_vector_3f){(float)x+w, (float)y+h, SF2D_DEFAULT_DEPTH};

float u = texture->width/(float)texture->pow2_w;
float v = texture->height/(float)texture->pow2_h;

vertices[0].texcoord = (sf2d_vector_2f){0.0f, 0.0f};
vertices[1].texcoord = (sf2d_vector_2f){u,    0.0f};
vertices[2].texcoord = (sf2d_vector_2f){0.0f, v};
vertices[3].texcoord = (sf2d_vector_2f){u,    v};

self->vertices[self->currentImage] = vertices;
```

}

//graphics.c
//If we found a SpriteBatch as the first argument, do this
for (int i = 0; i < spritebatch->currentImage; i++) {
                sf2d_draw_texture_multi(spritebatch->resource->texture, spritebatch->vertices[i], x, y, getCurrentColor()); 
            }`

Oddly, even though all this works it.. has issues.

![screenshot from 2016-04-01 08-59-00](https://cloud.githubusercontent.com/assets/6239208/14208064/7da11826-f7eb-11e5-8ccf-cdfdc92a2749.png)

It seems that drawing text (or perhaps any other operations) after what I've done ruins the drawing.
Any help as to fixing this would be greatly appreciated!

**Comment by xerpi** [comment]
Are you careful with the pointer returned by sf2d_pool_calloc? It's data gets freed after each frame on sf2d.

**Comment by TurtleP** [comment]
Hmm how should I be preserving it?

**Comment by xerpi** [comment]
You have to allocate it one each frame. If you want to fill an array of vertices and keep it for all the frames you should use regular malloc/memalign.
