### ISSUE TITLE
rendering a texture doesn't works in c++

### ISSUE THREAD

**Issue by cynosura15** [xerpi/sf2dlib#32]
In C it works like a charm, but in CPP when I try to render a texture, I get this error:

```
c:/Users/me/Desktop/3ds-game/source/Game.cpp: At global scope:
c:/Users/me/Desktop/3ds-game/source/Game.cpp:10:3: error: 'const<anonymous st
ruct> sprite1_img', declared using anonymous type, is used but never defined [-f
permissive]
 } sprite1_img;
```

Any idea about why it happens?

**Comment by xerpi** [comment]
Sorry for the delay, can you paste the struct definition here?

**Comment by cynosura15** [comment]
I don't remember what was the problem exactly, but I've solved it, _sorry_ :/

**Comment by xerpi** [comment]
OK, good to know, so I guess I can close this issue.
