### ISSUE TITLE
[BUG] Sample gives black screen on n3ds v9.9 ninjhax2

### ISSUE THREAD

**Issue by JerwuQu** [xerpi/sf2dlib#5]
I built the library and the sample that came with it. The sample works in Citra nightly but not on my actual device when launching it from the Homebrew Launcher.

**Comment by xerpi** [comment]
Maybe there's some stuff broken with ctrulib and ninjhax2. Could you try some simpler hello world?

**Comment by JerwuQu** [comment]
The only things I've tested on my n3ds so far are some ctrulib examples but they've all worked as expected. Will try to create the smallest possible application that shows the problem in a few minutes. Note that it's not only the graphics that aren't working, both screens turn black and I can't go back to Homebrew Launcher.

**Comment by JerwuQu** [comment]
Simply uncommenting the lines starting with `//--` makes this application freeze at a black screen on my n3ds with no way to turn back except for holding the power button. 

``` c
#include <3ds.h>
//-- #include <sf2d.h>

// Codez
int main(){
    // Init sf2d
    //-- sf2d_init();

    // Some variables
    u32 buttons;

    // Main loop
    while (aptMainLoop()) {
        // Read held buttons
        hidScanInput();
        buttons = hidKeysHeld();

        // Exit main loop if start is held
        if(buttons & KEY_START) break;
    }

    // Finish up
    //-- sf2d_fini();

    return 0;
}
```

**Comment by JerwuQu** [comment]
Worth noting is that it doesn't seem to freeze the first time the application is ran, but when I start it again it freezes and doesn't respond to the START-button. The normal application without sf2d works fine though.

EDIT: Confirmed to NOT freeze the first time.

Only applies to code above. Sample freezes on start.

**Comment by JerwuQu** [comment]
https://github.com/smealum/ctrulib/pull/143/
^ this commit seems to have broken sf2dlib

**Comment by fincs** [comment]
The problematic commit has been reverted in libctru for now, and the causes of the break will be investigated.

**Comment by JerwuQu** [comment]
Since this issue had more to do with ctrulib than sf2dlib and since the cause of the problem has been reverted, I'll close this.
