### ISSUE TITLE
GPU_KEEP -> GPU_STENCIL_KEEP

### ISSUE THREAD

**Issue by cloudburst** [xerpi/sf2dlib#7]
https://github.com/xerpi/sf2dlib/blob/master/libsf2d/source/sf2d.c#L154

https://github.com/smealum/ctrulib/commit/24fd71c4add247454c41812c16f4c207e84acdf6

**Comment by xerpi** [comment]
Fixed on 24eb5d337cccd769b5aeff9e05bfa87e10d53467.
